name: visual
description: A Bible reading tracker app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2

  shared_preferences: ^2.2.0
  http: ^1.6.0
  google_sign_in: ^6.3.0
  intl: ^0.19.0
  url_launcher: ^6.1.13
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
